import { mkdir, cp, access, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
for (const file of ['index.html','src/main.js','src/physics.js','src/styles.css','assets/city-vertical.png','assets/project-screens.png','assets/inter-latin.woff2']) await access(path.join(root,file));
const source = await readFile(path.join(root,'index.html'),'utf8');
if (!source.includes('lang="pt-BR"')) throw new Error('Missing document language');
await mkdir(path.join(root,'dist'),{recursive:true});
for (const entry of ['index.html','src','assets']) await cp(path.join(root,entry),path.join(root,'dist',entry),{recursive:true});
console.log('Build completo: dist/ — HTML, CSS, módulos JavaScript e assets locais.');
