export const projectOrder = ['guingas', 'elevamos', 'michelle', 'ferreira', 'guarana', 'painel'];

export const projects = {
  guingas: {
    name: 'Guinga’s Bar', category: 'Site e sistema',
    description: 'Uma plataforma para a noite do bar: do cardápio digital à fila do karaokê, com atualização em tempo real e gestão pelo celular.',
    challenge: 'Automatizar a fila do karaokê, organizar um repertório de cerca de 41 mil músicas e dar autonomia à equipe para cuidar da programação.',
    features: ['Fila em tempo real com chamada e avanço automáticos', 'Busca por nome, artista ou código em cerca de 41 mil músicas', 'Painel de gestão da fila, do repertório e dos flyers', 'Cardápio com 132 itens e busca que ignora acentos', 'PWA instalável com aviso quando chega a vez de cantar'],
    technologies: [
      {label:'HTML5',icon:'html5'}, {label:'CSS3',icon:'css3'}, {label:'JavaScript',icon:'javascript'},
      {label:'Firebase',icon:'firebase',detail:'Realtime Database, Authentication e Security Rules'},
      {label:'Cloudflare Workers',icon:'cloudflare',detail:'Worker com Cron Trigger para manter a fila em movimento'},
      {label:'PWA',icon:'responsive'}, {label:'Google Maps API'},
    ],
    preview: '/assets/optimized/hero-projects-guingas.5e7b84b0b094.webp',
    screen: '/assets/optimized/project-screens-guingas.cfaed9d7d128.webp',
    url: 'https://www.guingasbar.com/',
    pose: [-.12, -.28, .06],
  },
  elevamos: {
    name: 'Elevamos', category: 'Cursos e capacitação',
    description: 'Site de cursos de manutenção de elevadores, com páginas estáticas em Astro e um blog que a equipe pode atualizar pelo painel de conteúdo.',
    challenge: 'Apresentar a formação com clareza, facilitar a descoberta por novos alunos e dar autonomia à equipe para publicar artigos.',
    features: ['Site público pré-renderizado em HTML', 'Blog editável no Keystatic com login próprio', 'Menu mobile e mapa carregado sob clique', 'Capas de artigos com imagens responsivas em WebP e JPEG', 'SEO com sitemap, feed RSS e dados estruturados'],
    technologies: [
      {label:'Astro 7',icon:'astro',detail:'Páginas públicas estáticas e componentes .astro'},
      {label:'TypeScript',icon:'typescript'},
      {label:'CSS3',icon:'css3',detail:'CSS puro, com Figtree via Google Fonts'},
      {label:'JavaScript',icon:'javascript',detail:'JavaScript vanilla para menu mobile e mapa sob clique; nenhum framework no navegador do visitante'},
      {label:'Keystatic',detail:'CMS do blog com @keystatic/core e @keystatic/astro'},
      {label:'React 19 · painel',icon:'react',detail:'Usado apenas pelo Keystatic, fora do site público'},
      {label:'Markdoc',detail:'Formato dos artigos do blog'},
      {label:'Node.js',icon:'nodejs',detail:'Node.js ≥22.12, adaptador standalone e login próprio com node:crypto'},
      {label:'Sharp',detail:'Geração de variantes responsivas das capas no build'},
      {label:'Git / GitHub',icon:'github',detail:'Versionamento em repositório privado'},
    ],
    preview: '/assets/optimized/hero-projects-elevamos.dfaf29902f3c.webp',
    screen: '/assets/optimized/project-screens-elevamos.60f78ac180cc.webp',
    url: 'https://elevamoscursos.com.br/',
    pose: [-.08, .23, -.045],
  },
  michelle: {
    name: 'Michelle Sampaio', category: 'Marketing e social media',
    description: 'Portfólio de marketing e social media que reúne cases, criativos e vídeos em uma experiência responsiva, construída com HTML, CSS e JavaScript puros.',
    challenge: 'Valorizar a identidade profissional e reunir diferentes formatos de conteúdo em uma navegação clara, com uma estrutura enxuta e fácil de manter.',
    features: ['Carrossel de criativos com ampliação das imagens', 'Vídeo do case com player próprio', 'Publicações do Instagram com alternativa de exibição', 'Animações de entrada ao rolar a página', 'Layout responsivo com imagens otimizadas'],
    technologies: [
      {label:'HTML5',icon:'html5',detail:'HTML semântico e galeria com dialog nativo'},
      {label:'CSS3',icon:'css3',detail:'Variáveis nativas e estilos organizados por seção'},
      {label:'JavaScript',icon:'javascript',detail:'ES6+, sem frameworks ou dependências de runtime'},
      {label:'Cloudflare Workers',icon:'cloudflare',detail:'Assets estáticos com deploy automático integrado ao GitHub'},
      {label:'GitHub',icon:'github',detail:'Push no main dispara build e deploy pelo Cloudflare'},
      {label:'Google Fonts',detail:'Playfair Display nos títulos e Inter no corpo'},
    ],
    preview: '/assets/optimized/hero-projects-michelle.1d297b5793b6.webp',
    screen: '/assets/optimized/project-screens-michelle.506bce74f8c9.webp',
    url: 'https://portfolio-michelle-sampaio.michellesampaiorocha.workers.dev/',
    pose: [-.13, -.2, .04],
  },
  ferreira: {
    name: 'M.I. Ferreira', category: 'Construção civil',
    description: 'Landing page de construção civil com uma casa 3D interativa, construída por código com Three.js. A experiência funciona no navegador, com arquitetura estática, sem banco de dados ou backend de aplicação.',
    challenge: 'Apresentar a construção civil em uma experiência visual e interativa, integrando a arquitetura à navegação em celulares e desktops.',
    features: [
      'Casa 3D construída por código, com piscina, vegetação e interiores',
      'Materiais, iluminação, sombras e câmera renderizados com WebGL',
      'Movimento cinematográfico suave e controles em JavaScript',
      'Layout responsivo com ícones e anotações do hero em SVG',
      'Imagens em WebP e alternativa estática da casa',
    ],
    technologies: [
      {label:'HTML5',icon:'html5',detail:'Estrutura e conteúdo da página'},
      {label:'CSS3',icon:'css3',detail:'Visual, cores, efeitos e adaptação para celular e desktop'},
      {label:'JavaScript',icon:'javascript',detail:'JavaScript puro para interações, controles e animação suave da casa'},
      {label:'Three.js + WebGL',icon:'threejs',detail:'Renderização da casa 3D, materiais, iluminação, sombras e câmera'},
      {label:'SVG',detail:'Ícones, traços e marcações das anotações do hero'},
      {label:'WebP',detail:'Imagens otimizadas do céu e alternativa estática da casa'},
      {label:'Node.js + npm',icon:'nodejs',detail:'Ambiente de desenvolvimento e ferramentas de construção, sem backend de aplicação'},
      {label:'esbuild',detail:'Agrupamento e compactação do JavaScript para publicação'},
    ],
    preview: '/assets/optimized/hero-projects-ferreira.f5e9aec7cf30.webp',
    screen: '/assets/optimized/project-screens-ferreira.8be3e844e70b.webp',
    url: null,
    status: {label:'Projeto concluído',detail:'Publicação pendente'},
    pose: [-.09, .3, -.04],
  },
  guarana: {
    name: 'Guaraná Jesus', category: 'Experiência 3D',
    description: 'Uma experiência conceitual de marca com uma lata 3D no centro da narrativa. Câmera, luzes e animações acompanham a rolagem em uma página cinematográfica inspirada na identidade do Guaraná Jesus.',
    challenge: 'Transformar a apresentação de um produto em uma experiência imersiva, conectando a história, o sabor e a identidade visual da marca por meio de uma narrativa em movimento.',
    features: [
      'Lata 3D interativa com rotação por arraste e inércia',
      'Movimentos de câmera e transições sincronizados com a rolagem',
      'Iluminação dinâmica, reflexos, bolhas e partículas em profundidade',
      'Seis cenas que exploram o produto e sua origem no Maranhão',
      'Adaptação para mobile e suporte à preferência de movimento reduzido',
    ],
    technologies: [
      {label:'React',icon:'react',detail:'Interface e composição das seções'},
      {label:'Three.js + WebGL',icon:'threejs',detail:'Renderização da lata, iluminação e partículas'},
      {label:'React Three Fiber',detail:'Integração da cena Three.js com React'},
      {label:'GSAP + ScrollTrigger',detail:'Animações e transições conectadas à rolagem'},
      {label:'Lenis',detail:'Rolagem suave da experiência'},
      {label:'CSS Modules',icon:'css3',detail:'Estilos por componente e layout responsivo'},
      {label:'GLB',detail:'Modelo tridimensional da lata'},
      {label:'Cloudflare Workers',icon:'cloudflare',detail:'Publicação da página'},
    ],
    preview: '/assets/optimized/hero-projects-guarana.48c799fb756b.webp',
    screen: '/assets/optimized/project-screens-guarana.162e5331cf1e.webp',
    url: 'https://site-guaranajesus-modelo3d.paulo77-el.workers.dev/',
    pose: [-.1, -.25, .045],
  },
  painel: {
    name: 'Painel de Avaliações', category: 'EdTech · Dados e gestão',
    description: 'Plataforma privada que transforma planilhas de avaliações educacionais em indicadores claros para apoiar o acompanhamento pedagógico da escola, das turmas e de cada estudante.',
    challenge: 'Reunir fontes com formatos diferentes, preservar a confiabilidade dos resultados e permitir a análise pedagógica sem expor dados sensíveis de estudantes.',
    features: [
      'Visão geral com participação, defasagem e desempenho por componente',
      'Análises da Avaliação Diagnóstica e da Prova Paulista por período',
      'Ficha individual com trajetória, evolução e pontos de atenção',
      'Importação de planilhas com prévia, confirmação e reversão segura',
      'Acesso por perfil, sessões protegidas e trilha de auditoria',
    ],
    technologies: [
      {label:'HTML5',icon:'html5',detail:'Interface semântica de uma aplicação web responsiva'},
      {label:'CSS3',icon:'css3',detail:'Sistema visual próprio, sem framework de estilos'},
      {label:'JavaScript',icon:'javascript',detail:'Frontend e API em módulos JavaScript, sem framework de runtime'},
      {label:'Cloudflare Pages',icon:'cloudflare',detail:'Hospedagem do frontend e Pages Functions para a API'},
      {label:'Cloudflare D1',icon:'cloudflare',detail:'Banco SQLite com migrações e consultas parametrizadas'},
      {label:'Cloudflare R2',icon:'cloudflare',detail:'Armazenamento privado das planilhas importadas'},
      {label:'Web Crypto',detail:'Sessões, hashes e proteção de senhas com APIs nativas'},
      {label:'SVG',detail:'Gráficos de radar, evolução e distribuição feitos à mão'},
      {label:'Node.js',icon:'nodejs',detail:'Ambiente local e suítes próprias de testes de segurança e negócio'},
    ],
    preview: '/assets/optimized/hero-projects-painel.9bceb2a7d393.webp',
    slides: [
      { src: '/assets/optimized/hero-projects-painel.9bceb2a7d393.webp', caption: 'Visão geral · dados fictícios', alt: 'Demonstração do painel educacional com indicadores e gráfico de desempenho por matéria.' },
      { src: '/assets/optimized/painel-slide-login.2e1baa175e3e.webp', caption: 'Acesso ao painel · demonstração', alt: 'Tela de login do painel de avaliações, com identidade fictícia Escola Modelo.' },
      { src: '/assets/optimized/painel-slide-diagnostica.2dcf6c59fcff.webp', caption: 'Avaliação Diagnóstica · dados fictícios', alt: 'Filtros, participação, defasagem e distribuição de proficiência em Português e Matemática.' },
      { src: '/assets/optimized/painel-slide-turmas.20b6febf9160.webp', caption: 'Evolução e comparativo de turmas · dados fictícios', alt: 'Gráficos ilustrativos de evolução entre semestres e comparação de turmas fictícias.' },
      { src: '/assets/optimized/painel-slide-aluno.1cea29225dfd.webp', caption: 'Ficha individual · aluno e resultados fictícios', alt: 'Ficha do Aluno Demonstração com desempenho por componente e avaliação diagnóstica.' },
      { src: '/assets/optimized/painel-slide-trajetoria.a45fbd994b29.webp', caption: 'Trajetória e leitura dos dados · dados fictícios', alt: 'Gráficos de trajetória na Diagnóstica, média na Prova Paulista e pontos de acompanhamento.' },
      { src: '/assets/optimized/painel-slide-evolucao.e39743cdff1d.webp', caption: 'Evolução ao longo do ano · dados fictícios', alt: 'Tabela demonstrativa com resultados por componente curricular e bimestre.' },
      { src: '/assets/optimized/project-screens-painel.4d007c2f881b.webp', caption: 'Prévia mobile ilustrativa · dados fictícios', alt: 'Prévia ilustrativa do painel no celular, com participação, desempenho e evolução.' },
    ],
    screen: '/assets/optimized/project-screens-painel.4d007c2f881b.webp',
    url: null,
    status: {label:'Projeto privado',detail:'Acesso restrito à instituição'},
    pose: [-.08, .18, -.035],
  },
};
