export const projectOrder = ['guingas', 'elevamos', 'michelle', 'ferreira'];

export const projects = {
  guingas: {
    name: 'Guinga’s Bar', category: 'Site e sistema',
    description: 'Uma plataforma para a noite do bar: do cardápio digital à fila do karaokê, com atualização em tempo real e gestão pelo celular.',
    challenge: 'Automatizar a fila do karaokê, organizar um repertório de cerca de 41 mil músicas e dar autonomia à equipe para cuidar da programação.',
    features: ['Fila em tempo real com chamada e avanço automáticos', 'Busca por nome, artista ou código em cerca de 41 mil músicas', 'Painel de gestão da fila, do repertório e dos flyers', 'Cardápio com 132 itens e busca que ignora acentos', 'PWA instalável com aviso quando chega a vez de cantar'],
    technologies: [
      {label:'HTML5',icon:'html5'}, {label:'CSS3',icon:'css3'}, {label:'JavaScript',icon:'javascript'},
      {label:'Firebase',icon:'firebase',detail:'Realtime Database, Authentication e Security Rules'},
      {label:'Cloudflare Workers',icon:'cloudflare',detail:'Worker com Cron Trigger para manter a fila em movimento'},
      {label:'PWA',icon:'responsive'}, {label:'Google Maps API'},
    ],
    screen: '/assets/project-screens/guingas.png',
    url: 'https://www.guingasbar.com/',
    pose: [-.12, -.28, .06],
  },
  elevamos: {
    name: 'Elevamos', category: 'Cursos e capacitação',
    description: 'Site de cursos de manutenção de elevadores, com páginas estáticas em Astro e um blog que a equipe pode atualizar pelo painel de conteúdo.',
    challenge: 'Apresentar a formação com clareza, facilitar a descoberta por novos alunos e dar autonomia à equipe para publicar artigos.',
    features: ['Site público pré-renderizado em HTML', 'Blog editável no Keystatic com login próprio', 'Menu mobile e mapa carregado sob clique', 'Capas de artigos com imagens responsivas em WebP e JPEG', 'SEO com sitemap, feed RSS e dados estruturados'],
    technologies: [
      {label:'Astro 7',icon:'astro',detail:'Páginas públicas estáticas e componentes .astro'},
      {label:'TypeScript',icon:'typescript'},
      {label:'CSS3',icon:'css3',detail:'CSS puro, com Figtree via Google Fonts'},
      {label:'JavaScript',icon:'javascript',detail:'JavaScript vanilla para menu mobile e mapa sob clique; nenhum framework no navegador do visitante'},
      {label:'Keystatic',detail:'CMS do blog com @keystatic/core e @keystatic/astro'},
      {label:'React 19 · painel',icon:'react',detail:'Usado apenas pelo Keystatic, fora do site público'},
      {label:'Markdoc',detail:'Formato dos artigos do blog'},
      {label:'Node.js',icon:'nodejs',detail:'Node.js ≥22.12, adaptador standalone e login próprio com node:crypto'},
      {label:'Sharp',detail:'Geração de variantes responsivas das capas no build'},
      {label:'Git / GitHub',icon:'github',detail:'Versionamento em repositório privado'},
    ],
    screen: '/assets/project-screens/elevamos.png',
    url: 'https://elevamoscursos.com.br/',
    pose: [-.08, .23, -.045],
  },
  michelle: {
    name: 'Michelle Sampaio', category: 'Marketing e social media',
    description: 'Portfólio de marketing e social media que reúne cases, criativos e vídeos em uma experiência responsiva, construída com HTML, CSS e JavaScript puros.',
    challenge: 'Valorizar a identidade profissional e reunir diferentes formatos de conteúdo em uma navegação clara, com uma estrutura enxuta e fácil de manter.',
    features: ['Carrossel de criativos com ampliação das imagens', 'Vídeo do case com player próprio', 'Publicações do Instagram com alternativa de exibição', 'Animações de entrada ao rolar a página', 'Layout responsivo com imagens otimizadas'],
    technologies: [
      {label:'HTML5',icon:'html5',detail:'HTML semântico e galeria com dialog nativo'},
      {label:'CSS3',icon:'css3',detail:'Variáveis nativas e estilos organizados por seção'},
      {label:'JavaScript',icon:'javascript',detail:'ES6+, sem frameworks ou dependências de runtime'},
      {label:'Cloudflare Workers',icon:'cloudflare',detail:'Assets estáticos com deploy automático integrado ao GitHub'},
      {label:'GitHub',icon:'github',detail:'Push no main dispara build e deploy pelo Cloudflare'},
      {label:'Google Fonts',detail:'Playfair Display nos títulos e Inter no corpo'},
    ],
    screen: '/assets/project-screens/michelle.png',
    url: 'https://portfolio-michelle-sampaio.michellesampaiorocha.workers.dev/',
    pose: [-.13, -.2, .04],
  },
  ferreira: {
    name: 'M.I. Ferreira', category: 'Construção civil',
    description: 'Landing page de construção civil com uma experiência de visualização de uma casa em 3D. Publicação em preparação.',
    challenge: 'Apresentar a construção civil em uma página visual, com a arquitetura como parte da experiência.',
    features: ['Landing page de apresentação', 'Modelo tridimensional de uma casa'],
    technologies: [],
    screen: '/assets/project-screens/ferreira.png',
    url: null,
    pose: [-.09, .3, -.04],
  },
};
